<a href="https://colab.research.google.com/github/jarvis-control/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

In [3]:
import pandas as pd

In [4]:
mydataset = {
  'cars': ["Aston Martin", "BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Bugatti"],
  'counts': [3, 7, 4, 2, 4, 5, 8]
}

df = pd.DataFrame(mydataset)
print(df)

           cars  counts
0  Aston Martin       3
1           BMW       7
2         Volvo       4
3          Ford       2
4         Tesla       4
5       Ferrari       5
6       Bugatti       8

In [ ]:
# head() - first rows (default: 5 rows)
df.head()

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       4
4  Ferrari       5

In [ ]:
# tail() - last rows (default: 5 rows)
df.tail(3)

      cars  counts
3    Tesla       4
4  Ferrari       5
5  Bugatti       8

In [ ]:
# shape - shows how many rows and columns the DataFrame has
df.shape

(6, 2)

In [ ]:
# columns - shows column names
df.columns

Index(['cars', 'counts'], dtype='object')

In [ ]:
# dtypes - shows the data type of each column
df.dtypes

cars      object
counts     int64
dtype: object

In [5]:
# describe() - gives summary statistics. By default, it focuses on numerical columns
# describe(include="all") - includes text columns too
df.describe()

         counts
count  7.000000
mean   4.714286
std    2.138090
min    2.000000
25%    3.500000
50%    4.000000
75%    6.000000
max    8.000000

In [6]:
# iloc - selects by integer position. Think: position number
df.iloc[2:]

      cars  counts
2    Volvo       4
3     Ford       2
4    Tesla       4
5  Ferrari       5
6  Bugatti       8

In [ ]:

# loc - selects by label. Think: row label and column label
df.loc[2:5, "cars"]

2      Volvo
3       Ford
4      Tesla
5    Ferrari
Name: cars, dtype: object

In [ ]:
print(df)

           cars  counts
0  Aston Martin       3
1           BMW       7
2         Volvo       4
3          Ford       2
4         Tesla       4
5       Ferrari       5
6       Bugatti       8

In [ ]:
# Filtering means showing only rows that match a condition
df[df["counts"] >= 4]

      cars  counts
1      BMW       7
2    Volvo       4
4    Tesla       4
5  Ferrari       5
6  Bugatti       8

In [ ]:
# df.mean(numeric_only=True) - Average
df["counts"].mean()

np.float64(4.714285714285714)

In [ ]:
# sum() - Adds values
df.sum()

cars      Aston MartinBMWVolvoFordTeslaFerrariBugatti
counts                                             33
dtype: object

In [ ]:
# min() - Smallest value
df.min()

cars      Aston Martin
counts               2
dtype: object

In [ ]:
# max() - Largest value
df.max()

cars      Volvo
counts        8
dtype: object

In [ ]:
# median() - Middle value after sorting
df.median(numeric_only=True)

counts    4.0
dtype: float64

In [ ]:
# count() - Counts non-empty values
df.count()

cars      7
counts    7
dtype: int64

In [ ]:
# std() - Standard deviation - how spread out values are
df.std(numeric_only=True)

counts    2.13809
dtype: float64

In [8]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [ ]:
# isnull() -
df_missing.isnull()

    cars  counts
0  False   False
1  False   False
2   True    True
3  False   False
4  False   False
5   True   False
6  False    True

In [ ]:
# sum() -
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [10]:
# dropna() - removes missing data. The behavior depends on what you ask it to remove
# dropna(axis=0) - means columns. Since both cars and counts contain missing values, both columns may disappear
# dropna(axis=1) -

df_missing.dropna(axis=0)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [ ]:
# dropna(subset=['counts']) - this removes only rows where counts is missing. If cars is missing but counts exists, that row stays
df_missing.dropna(subset=['counts'])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0

In [ ]:
# fillna() - replaces missing values
# This replaces missing car names with "unknown" and missing counts with 0
df_missing.fillna({"cars": "unkown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2   unkown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5   unkown     9.0
6     Ford     0.0

In [ ]:
# Reading and Saving Files
# df = pd.read_csv("Titanic-Dataset.csv")
df = pd.read_excel("text.xlsx")

df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Saves an existing DataFrame in an Excel format
df.to_excel("test.xlsx")

In [ ]:
# DataFrame = entire table
# Series = one column from that table
# Series = Values + Index

# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [ ]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [ ]:
cars_series = df_missing["cars"]

print(cars_series)

0        BMW
1      Volvo
2       None
3      Tesla
4    Ferrari
5       None
6       Ford
Name: cars, dtype: object